### ISSUE TITLE
Add support for Downloading Collections

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [imwaitingnow/WorkshopDL#12]
**Provide the game's name below.**
Garry's Mod

**Steam storepage. (Optional)**
https://store.steampowered.com/app/4000/Garrys_Mod/

**Additional context**
i want to download all the addons from the collections at once
#
###### i do not have access to labels

**Comment by misaka10843** [comment]
![image](https://github.com/imwaitingnow/WorkshopDL/assets/69132853/bbeed5ac-528b-467e-992e-3b5ee7e0aba1)
you can try using this

**Comment by GuestSneezeOSDev** [comment]
thank you i have 1 more question
