### ISSUE TITLE
Program flickering and unusable

### ISSUE THREAD

**Issue by Anime-Forevere** [imwaitingnow/WorkshopDL#5]
**Describe the bug**
When I try to use the program, it starts to flicker and clears all fields, which makes app unusable.

**To Reproduce**
Open app, see it flicker

**Expected behavior**
App should be working normally

**Screenshots** (Optional)
https://github.com/imwaitingnow/WorkshopDL/assets/56559528/cea2e44c-3d26-4c8d-8b1e-291d9bac463e

**Desktop (please complete the following information):**
 - Version - 2.0.0
 - Windows 11 22H2 (22621)

**Additional context**
I'm new to this program and may not understand something, but I think it is a bug.

**Comment by imwaitingnow** [comment]
is steamcmd.exe in the steamcmd folder

**Comment by Anime-Forevere** [comment]
Reinstalling the program seemed to make it work, maybe steamcmd didn't get initialized/downloaded.

**Comment by ARKYmouse** [comment]
I'm experiencing this problem as well. Nowhere is it clear where I need to install WorkshopDL in order for it to read the directory path to the steamcmd folder. Do I need to explicitly run setup and allow it to install to "C:\WorkshopDL\", or am I free to place it in a different directory?

**Comment by perigozin** [comment]
same problem here. it's not solved/completed

**Comment by taylorflatt** [comment]
The application might not have permissions to write to the directory you have saved it to. Obviously this could be better handled but that might be why you're having the issue.
